### PR TITLE
Monitoring works with FileChooserDialog; GTK+ 3.10 friendly Quit accelerator; Update Readme; Check if doc.index is nil; Add support for images in local directory; Allow multiple app instances

### PR DESCRIPTION
**Pull request by xHN35RQ**
I made some fixes and enhancements, please look over my contributions. I am new to Lua, so I have probably made mistakes, or perhaps written the code in un-Lua way.

Thanks for such a great app! I love the responsive table of contents... very handy. Showdown has all the features I was looking for in a markdown viewer.

### CODE REVIEW

**Comment by craigbarnes** [comment]
Thanks for the pull request! I'll try to take a closer look at this in the next couple of days.

For the short term I'll probably merge everything here and make a new release soon. Longer term I was planning to rewrite Showdown in Vala, to do away with the complications of handling/documenting the Lua dependencies and also to avoid using `lgi`, which is quite buggy and under-maintained these days.

**Comment by xHN35RQ** [comment]
Ok cool! Thanks for your response. I was actually thinking about a re-write in Python since it is better suited to this sort of work but have done no work on it yet. I'm impressed with Lua so far. Vala is however the proper choice for a Gnome/GTK+ app.

Something else that would be cool is to add a menu to choose from different CSS, have a toggle-able TOC (sometimes I want just the text in a single-column) and have an Export or Print feature that pushes out a proper 

Also, would you consider using pandoc instead of discount? I'm not sure, but I think pandoc is better maintained at this point?

**Comment by craigbarnes** [comment]
> Something else that would be cool is to add a menu to choose from different CSS, have a toggle-able TOC (sometimes I want just the text in a single-column) and have an Export or Print feature ...

Those suggestions all sound good to me.

> Also, would you consider using pandoc instead of discount? I'm not sure, but I think pandoc is better maintained at this point?

I've been wanting to switch away from discount for a while, but I think I'd prefer to use [libcmark](https://github.com/jgm/cmark) over Pandoc. They're both the work of John MacFarlane, but libcmark has 0 dependencies, whereas Pandoc has about 30. I guess another option would be to just pipe the input into a (configurable) external command.

**Comment by xHN35RQ** [comment]
Ah yes, libcmark is preferable. I'm not partial to pandoc but it's preferable over discount and far easier to install.

I'll add my suggestions as issues for tracking.

**Comment by xHN35RQ** [comment]
Also have you considered using something other than Webkit2? Perhaps [Electron](https://github.com/atom/electron) or [https://github.com/nwjs/nw.js](NW.js)?

**Comment by craigbarnes** [comment]
> Also have you considered using something other than Webkit2? Perhaps Electron or NW.js?

Not really. I think WebKit2GTK is by far the best suited/integrated choice for a GTK app.

I've started porting to Vala already in the [`vala`](https://github.com/craigbarnes/showdown/commits/vala) branch. I'll try to get it up to par with the `master` branch first, then I'll see about translating your improvements over to Vala.

**Comment by xHN35RQ** [comment]
Niiiice!

**Comment by craigbarnes** [comment]
Already done in `vala` branch:

* [x] Setting `base_uri` to allow loading local images
* [x] GTK 3.10 compatibility

`TODO` in `vala` branch:

* [ ] Automatic refresh
* [ ] Mention Discount requirement in `README.md`

Obsolete in `vala` branch:

* [ ] ~~Random `application_id`~~ -- the `Gtk.Application` class already allows multiple `Gtk.ApplicationWindow` instances per app. The signal handlers just need setting up correctly.
* [ ] ~~Check `doc.index` for `nil`~~

**Comment by xHN35RQ** [comment]
> ~~Random application_id~~

Yep, that was a dirty hack :stuck_out_tongue_winking_eye:

**Comment by craigbarnes** [comment]
Closing. The one remaining todo item is now #22.

**Pull request closed without merging**
